### ISSUE TITLE
Case Sensitive

### ISSUE THREAD

**Issue by nigamanthsrivatsan** [aayushgenius/Genius-The-Python-chatbot#1]
Hello, @aayushgenius

Your program is case sensitive and therefore not a "good" chat-bot. 
For instance if a user says "Hi" then the str(input()) would be "Hi" whereas you're checking for "hi" and "hello".

This makes the chatbot hard to use, you should either inform the user prior to keep everything in lowercase or fix this issue.

**Comment by aayushgenius** [comment]
I don't work on these types of projects anymore, most of mine are private
